services:
  web-app:
    container_name: frontend-service
    build:
      context: ./web-app
    ports:
      - "127.0.0.1:3000:80"
    networks:
      - app-net

  gateway-service:
    container_name: gateway-service
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_PATH: services/gateway-service
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      - CHAT_URI=http://chat-service:8082
      - SIGNALING_URI=ws://signaling-service:8083
      - AI_URI=http://ai-service:8084
      - ANALYTICS_URI=http://analytics-service:8085
      - ROOM_URI=http://room-service:8086
      - USER_URI=http://user-service:8087
      - MEDIA_URI=http://media-service:8888
      - KEYCLOAK_CLIENT_SECRET=${KEYCLOAK_CLIENT_SECRET}
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI=https://auth.voicemessenger.mywire.org/realms/voice-messenger
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI=http://keycloak:9090/realms/voice-messenger/protocol/openid-connect/certs
    networks:
      - app-net

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:26.0.5
    command: start-dev
    environment:
      - KC_DB=postgres
      - KC_DB_URL_HOST=${INFRA_HOST}
      - KC_DB_URL_PORT=${POSTGRES_PORT}
      - KC_DB_URL_DATABASE=${POSTGRES_DB}
      - KC_DB_USERNAME=${POSTGRES_USER}
      - KC_DB_PASSWORD=${POSTGRES_PASSWORD}
      - KC_HOSTNAME_STRICT=false
      - KC_HTTP_ENABLED=true
      - KC_PROXY_HEADERS=xforwarded
      - KC_HTTP_PORT=9090
      - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
    ports:
      - "127.0.0.1:9090:9090"
    networks:
      - app-net

  chat-service:
    container_name: chat-service
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_PATH: services/chat-service
    environment:
      - INFRA_HOST=${INFRA_HOST}
      - STOMP_RELAY_HOST=${INFRA_HOST}
      - STOMP_RELAY_PORT=61613
      - STOMP_RELAY_LOGIN=${RABBITMQ_USER}
      - STOMP_RELAY_PASSCODE=${RABBITMQ_PASSWORD}
      - SPRING_RABBITMQ_HOST=${INFRA_HOST}
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=${RABBITMQ_USER}
      - SPRING_RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - DB_HOST=${INFRA_HOST}
      - MONGO_PORT=${MONGO_PORT_CHAT}
      - MONGO_USER=${MONGO_ROOT_USER}
      - MONGO_PASS=${MONGO_ROOT_PASSWORD}
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI=https://auth.voicemessenger.mywire.org/realms/voice-messenger
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI=http://keycloak:9090/realms/voice-messenger/protocol/openid-connect/certs
    networks:
      - app-net

  room-service:
    container_name: room-service
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_PATH: services/room-service
    environment:
      - INFRA_HOST=${INFRA_HOST}
      - STOMP_RELAY_HOST=${INFRA_HOST}
      - STOMP_RELAY_PORT=61613
      - STOMP_RELAY_LOGIN=${RABBITMQ_USER}
      - STOMP_RELAY_PASSCODE=${RABBITMQ_PASSWORD}
      - SPRING_RABBITMQ_HOST=${INFRA_HOST}
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=${RABBITMQ_USER}
      - SPRING_RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - DB_HOST=${INFRA_HOST}
      - MONGO_PORT=${MONGO_PORT_ROOMS}
      - MONGO_USER=${MONGO_ROOT_USER}
      - MONGO_PASS=${MONGO_ROOT_PASSWORD}
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI=https://auth.voicemessenger.mywire.org/realms/voice-messenger
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI=http://keycloak:9090/realms/voice-messenger/protocol/openid-connect/certs
    networks:
      - app-net

  signaling-service:
    container_name: signaling-service
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_PATH: services/signaling-service
    environment:
      - INFRA_HOST=${INFRA_HOST}
      - STOMP_RELAY_HOST=${INFRA_HOST}
      - STOMP_RELAY_PORT=61613
      - STOMP_RELAY_LOGIN=${RABBITMQ_USER}
      - STOMP_RELAY_PASSCODE=${RABBITMQ_PASSWORD}
      - SPRING_RABBITMQ_HOST=${INFRA_HOST}
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=${RABBITMQ_USER}
      - SPRING_RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI=https://auth.voicemessenger.mywire.org/realms/voice-messenger
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI=http://keycloak:9090/realms/voice-messenger/protocol/openid-connect/certs
    networks:
      - app-net

  ai-service:
    container_name: ai-service
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_PATH: services/ai-service
    environment:
      - SPRING_RABBITMQ_HOST=${INFRA_HOST}
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=${RABBITMQ_USER}
      - SPRING_RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - DB_HOST=${INFRA_HOST}
      - MONGO_PORT=${MONGO_PORT_CHAT}
      - MONGO_USER=${MONGO_ROOT_USER}
      - MONGO_PASS=${MONGO_ROOT_PASSWORD}
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI=https://auth.voicemessenger.mywire.org/realms/voice-messenger
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI=http://keycloak:9090/realms/voice-messenger/protocol/openid-connect/certs
      - AI_API_KEY=${AI_API_KEY}
      - AI_URL=${AI_URL}
    networks:
      - app-net

  analytics-service:
    container_name: analytics-service
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_PATH: services/analytics-service
    environment:
      - DB_HOST=${INFRA_HOST}
      - MONGO_PORT=${MONGO_PORT_ANALYTICS}
      - MONGO_USER=${MONGO_ROOT_USER}
      - MONGO_PASS=${MONGO_ROOT_PASSWORD}
      - SPRING_RABBITMQ_HOST=${INFRA_HOST}
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=${RABBITMQ_USER}
      - SPRING_RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI=https://auth.voicemessenger.mywire.org/realms/voice-messenger
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI=http://keycloak:9090/realms/voice-messenger/protocol/openid-connect/certs
    networks:
      - app-net

  media-service:
    container_name: media-service
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_PATH: services/media-service
    environment:
      - LIVEKIT_API_KEY=${LIVEKIT_API_KEY}
      - LIVEKIT_API_SECRET=${LIVEKIT_API_SECRET}
      - LIVEKIT_EXTERNAL_URL=${LIVEKIT_EXTERNAL_URL}
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI=https://auth.voicemessenger.mywire.org/realms/voice-messenger
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI=http://keycloak:9090/realms/voice-messenger/protocol/openid-connect/certs
    networks:
      - app-net

  livekit:
    image: livekit/livekit-server:latest
    container_name: voice-livekit-1
    command: --config /livekit.yaml
    volumes:
      - "./config/livekit.yaml:/livekit.yaml"
    environment:
      - "LIVEKIT_KEYS=${LIVEKIT_API_KEY}: ${LIVEKIT_API_SECRET}"
      - LIVEKIT_REDIS_ADDRESS=${INFRA_HOST}:${REDIS_PORT}
      - LIVEKIT_REDIS_PASSWORD=${REDIS_PASSWORD}
      - LIVEKIT_RTC_NAT_1_TO_1_IPS=3.71.11.3
      - LIVEKIT_RTC_USE_EXTERNAL_IP=false
      - LIVEKIT_RTC_PORT_RANGE_START=50000
      - LIVEKIT_RTC_PORT_RANGE_END=50050
    ports:
      - "127.0.0.1:7880:7880"
      - "7881:7881"
      - "50000-50050:50000-50050/udp"
    networks:
      - app-net

  user-service:
    container_name: user-service
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_PATH: services/user-service
    environment:
      - INFRA_HOST=${INFRA_HOST}
      - DB_HOST=${INFRA_HOST}
      - MONGO_PORT=${MONGO_PORT_USERS}
      - MONGO_USER=${MONGO_ROOT_USER}
      - MONGO_PASS=${MONGO_ROOT_PASSWORD}
      - SPRING_RABBITMQ_HOST=${INFRA_HOST}
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=${RABBITMQ_USER}
      - SPRING_RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - STOMP_RELAY_HOST=${INFRA_HOST}
      - STOMP_RELAY_PORT=61613
      - STOMP_RELAY_LOGIN=${RABBITMQ_USER}
      - STOMP_RELAY_PASSCODE=${RABBITMQ_PASSWORD}
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI=https://auth.voicemessenger.mywire.org/realms/voice-messenger
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI=http://keycloak:9090/realms/voice-messenger/protocol/openid-connect/certs
    networks:
      - app-net

networks:
  app-net:
    driver: bridge