version: '3.8'

services:
  gateway-service:
    container_name: gateway-service
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_PATH: services/gateway-service
    ports:
      - "8080:8080"
    environment:
      - AUTH_URI=http://auth-service:8081
      - CHAT_URI=http://chat-service:8082
      - SIGNALING_URI=ws://signaling-service:8083
      - AI_URI=http://ai-service:8084
      - ANALYTICS_URI=http://analytics-service:8085
      - KEYCLOAK_CLIENT_SECRET=${KEYCLOAK_CLIENT_SECRET}
    networks:
      - app-net

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:26.0.5
    command: start-dev
    environment:
      - KC_DB=postgres
      - KC_DB_URL_HOST=${INFRA_HOST}
      - KC_DB_URL_PORT=${POSTGRES_PORT}
      - KC_DB_URL_DATABASE=${POSTGRES_DB}
      - KC_DB_USERNAME=${POSTGRES_USER}
      - KC_DB_PASSWORD=${POSTGRES_PASSWORD}
      - KC_HOSTNAME_STRICT=false
      - KC_HTTP_ENABLED=true
      - KC_HTTP_PORT=9090
      - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
    ports:
      - "9090:9090"
    networks:
      - app-net

  chat-service:
    container_name: chat-service
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_PATH: services/chat-service
    environment:
      - DB_HOST=${INFRA_HOST}
      - MONGO_PORT=${MONGO_PORT_CHAT}
      - MONGO_USER=${MONGO_ROOT_USER}
      - MONGO_PASS=${MONGO_ROOT_PASSWORD}
    networks:
      - app-net

  signaling-service:
    container_name: signaling-service
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_PATH: services/signaling-service
    networks:
      - app-net

  ai-service:
    container_name: ai-service
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_PATH: services/ai-service
    environment:
      - DB_HOST=${INFRA_HOST}
      - MONGO_PORT=${MONGO_PORT_CHAT}
      - MONGO_USER=${MONGO_ROOT_USER}
      - MONGO_PASS=${MONGO_ROOT_PASSWORD}
    networks:
      - app-net

  analytics-service:
    container_name: analytics-service
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_PATH: services/analytics-service
    environment:
      - DB_HOST=${INFRA_HOST}
      - MONGO_PORT=${MONGO_PORT_ANALYTICS}
      - MONGO_USER=${MONGO_ROOT_USER}
      - MONGO_PASS=${MONGO_ROOT_PASSWORD}
    networks:
      - app-net

  livekit:
    image: livekit/livekit-server:latest
    container_name: voice-livekit-1
    command: --config /livekit.yaml
    ports:
      - "7880:7880"
      - "50000-50010:50000-50010/udp"
    volumes:
      - ./livekit.yaml:/livekit.yaml
    environment:
      - LIVEKIT_KEYS=${LIVEKIT_API_KEY}:${LIVEKIT_API_SECRET}
      - LIVEKIT_REDIS_ADDRESS=redis://:${REDIS_PASSWORD}@${INFRA_HOST}:${REDIS_PORT}
    networks:
      - app-net

networks:
  app-net:
    driver: bridge