services:
  auth-db:
    image: postgres:16-alpine
    container_name: auth-db
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - auth_db_data:/var/lib/postgresql/data
    networks:
      - voice-network

  chat-ai-db:
    image: mongo:6.0
    container_name: chat-ai-db
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - chat_ai_db_data:/data/db
    networks:
      - voice-network

  analytics-db:
    image: mongo:6.0
    container_name: analytics-db
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
    ports:
      - "27018:27017"
    volumes:
      - analytics_db_data:/data/db
    networks:
      - voice-network

  room-db:
    image: mongo:6.0
    container_name: room-db
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
    ports:
      - "27019:27017"
    volumes:
      - room_db_data:/data/db
    networks:
      - voice-network


  redis:
    image: redis:7-alpine
    container_name: infra-redis
    restart: always
    command: ["redis-server", "--bind", "0.0.0.0", "--requirepass", "${REDIS_PASSWORD}", "--appendonly", "no"]
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - voice-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"             # AMQP
      - "61613:61613"           # STOMP (Java - Front)
      - "127.0.0.1:15672:15672" # GUI
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    command: /bin/sh -c "rabbitmq-plugins enable --offline rabbitmq_stomp rabbitmq_management && rabbitmq-server"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - voice-network
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "-q", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  auth_db_data:
  chat_ai_db_data:
  analytics_db_data:
  room_db_data:
  redis_data:
  rabbitmq_data:

networks:
  voice-network:
    name: voice-network
    driver: bridge