server:
  port: 8082
spring:
  application:
    name: chat-service
  data:
    mongodb:
      uri: mongodb://${MONGO_USER}:${MONGO_PASS}@${DB_HOST}:${MONGO_PORT}/chat_db?authSource=admin

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:9090/realms/voice-messenger
          jwk-set-uri: http://keycloak:9090/realms/voice-messenger/protocol/openid-connect/certs